version: "3.4"

services:
  lb:
    image: dockercloud/haproxy:latest
    links:
      - looker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mysql
      - looker

  looker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LOOKER_LICENSE_KEY
        - LOOKER_LICENSE_EMAIL
        - LOOKER_VERSION
    volumes:
      - ./data/looker:/srv/data/looker
    links:
      - "mysql"
    depends_on:
      - mysql

  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
